[build]
  Command = "yarn build"
  Functions = "lambda"
  Publish = "build"
        
[context.develop.environment]
  REACT_APP_GH_CLIENT_ID = "61bcbf0a23331c885af0"
  REACT_APP_GH_OAUTH_REDIRECT_URL = "http://localhost:8888"